name: klondike
description: Klondike Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

flutter:
  assets:
    - assets/images/